// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzWUpZ7SE9u_1JtW8NHRt4004GJk4zRM8',
    appId: '1:785934730792:web:06c23b3404f6573682d71d',
    messagingSenderId: '785934730792',
    projectId: 'scribly-notes-app',
    authDomain: 'scribly-notes-app.firebaseapp.com',
    storageBucket: 'scribly-notes-app.firebasestorage.app',
    measurementId: 'G-FBX40J44P9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5wLq8FG2xzQTxShGA2KAIQEXe8N66Ycg',
    appId: '1:785934730792:android:289bc3e5d6304f9082d71d',
    messagingSenderId: '785934730792',
    projectId: 'scribly-notes-app',
    storageBucket: 'scribly-notes-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6Xuw1ZBcDuXp0cYwPcv7xzC6zXoFaB8I',
    appId: '1:785934730792:ios:14ff9ba4c542158f82d71d',
    messagingSenderId: '785934730792',
    projectId: 'scribly-notes-app',
    storageBucket: 'scribly-notes-app.firebasestorage.app',
    iosBundleId: 'com.example.notesApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6Xuw1ZBcDuXp0cYwPcv7xzC6zXoFaB8I',
    appId: '1:785934730792:ios:14ff9ba4c542158f82d71d',
    messagingSenderId: '785934730792',
    projectId: 'scribly-notes-app',
    storageBucket: 'scribly-notes-app.firebasestorage.app',
    iosBundleId: 'com.example.notesApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzWUpZ7SE9u_1JtW8NHRt4004GJk4zRM8',
    appId: '1:785934730792:web:f79217928760c23482d71d',
    messagingSenderId: '785934730792',
    projectId: 'scribly-notes-app',
    authDomain: 'scribly-notes-app.firebaseapp.com',
    storageBucket: 'scribly-notes-app.firebasestorage.app',
    measurementId: 'G-C5JXHZP6F6',
  );
}
